# development environment
# based on `docker-compose.yml`

version: '3.2'

services:
  wp:
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
    environment:
      WORDPRESS_DEBUG: 1
