# development environment
# based on `docker-compose.yml`

version: '3.2'

services:
  wp:
    build: ./wp
    volumes:
      - type: bind
        source: ./wp/code
        target: /var/www/html
      - type: bind
        source: ./wp/php.development.ini
        target: /usr/local/etc/php/php.ini
    ports:
      - 8000:80
    environment:
      WORDPRESS_DEBUG: 1
