# Production environment
# Based on 'docker-compose.yml'
#
# 'jwilder/nginx-proxy' and 'jrcs/letsencrypt-nginx-proxy-companion' containers
# are expected to be running connected to 'proxy' network.

version: '3.2'

services:
  db:
    restart: unless-stopped
    networks:
      - default
  wp:
    restart: unless-stopped
    networks:
      - default
      - proxy
    environment:
      - VIRTUAL_HOST=piotrjanczyk.tk
      - LETSENCRYPT_HOST=piotrjanczyk.tk
      - LETSENCRYPT_EMAIL=pjanczyk97@gmail.com

networks:
  proxy:
    external: true
